openapi: 3.0.3
info:
  title: tRPC OpenAPI
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /get-user:
    get:
      operationId: query.getUser
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                required:
                  - id
                  - name
                additionalProperties: false
        default:
          $ref: '#/components/responses/error'
components:
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
  responses:
    error:
      description: Error response
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              code:
                type: string
              issues:
                type: array
                items:
                  type: object
                  properties:
                    message:
                      type: string
                  required:
                    - message
                  additionalProperties: false
            required:
              - message
              - code
            additionalProperties: false
